config/routes.rb
Ritly::Application.routes.draw do

	# all standard Restful CRUD routes (listed example for rlinks, also includes users, sessions)
	#      root GET     /                          rlinks#index
	#     rlinks GET    /rlinks(.:format)          rlinks#index
	#            POST   /rlinks(.:format)          rlinks#create
	#  new_rlink GET    /rlinks/new(.:format)      rlinks#new
	# edit_rlink GET    /rlinks/:id/edit(.:format) rlinks#edit
	#      rlink GET    /rlinks/:id(.:format)      rlinks#show
	#            PATCH  /rlinks/:id(.:format)      rlinks#update
	#            PUT    /rlinks/:id(.:format)      rlinks#update
	#            DELETE /rlinks/:id(.:format)      rlinks#destroy
	resources	:rlinks, :users, :sessions

	# create a route for root link, sending to main/home page (index)
	root to: 'rlinks#index'

	# custom application routes
	get '/rlinks/go/:link_token', to: "rlinks#route_link"

	# list routes for user login logout
	get '/signup' => 'users#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  get'/signin' => 'sessions#new'


end

app/models/rlink.rb
# == Schema Information
#
# Table name: rlinks
#
#  id            :integer          not null, primary key
#  link          :string(255)
#  random_string :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#

class Rlink < ActiveRecord::Base
	validates :random_string, uniqueness: true

	def self.url_lookup_by_token(link_token)

		# search for the record with provided link token (aka random_string)
		lookup_rec = self.find_by(random_string: link_token)

		# TODO - consider adding index on random_string, improve search performance

		if lookup_rec == nil		# no record was found, return nil
			lookup_url = nil
		else
			lookup_url = lookup_rec.link
		
			# check url, prepend scheme if missing
			lookup_url.prepend('http://') if URI(lookup_url).scheme == nil
		end

		return lookup_url
	end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  # this line not needed when using Rails 4, and  (require & permit with params)
  # attr_accessible :name, :email, :password, :password_confirmation
  
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

    private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rlinks_controller.rb
class RlinksController < ApplicationController
  before_filter :signed_in_user, only: [:create, :new, :edit, :update]

	# home/index page GET, shows a list of current links
	def index
		@rlinks = Rlink.all
	end

	# GETs a form to create a new link
	def new
		@rlink = Rlink.new
	end

	# POSTs the results from new, creating a new link
	def create
		new_rlink = params.require(:rlink).permit(:link, :random_string)
		rlink = Rlink.create(new_rlink)
   	redirect_to rlink
	end

	# GETs a form (disabled) to display a given link
	def show
		@current_link = Rlink.find(params[:id])
	end

	# GETs a form to edit a link
	def edit
		@rlink = Rlink.find(params[:id])
	end

	# PATCH saves the updated attributes
	def update
		updated_info = params.require(:rlink).permit(:link, :random_string)
		rlink = Rlink.find(params[:id])
		rlink.update_attributes(updated_info)
		redirect_to rlink
	end

	# DELETE destroy the selected link
	def destroy
		rlink = Rlink.find(params[:id])
		rlink.destroy

		redirect_to action: :index
	end

	# GET - user entered URL with go/token
	def route_link
		new_url = Rlink.url_lookup_by_token(params[:link_token])
		new_url == nil ? (render :token_not_found) : (redirect_to new_url)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user=User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect to the user's show page.
      sign_in user
      redirect_to user
    else
      # Create an error message and re-render the signin form.
      flash.now[:error]='Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
      sign_out
      redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new()
  end

  def create
    new_user = params.require(:user).permit(:name, :email, :password, :password_confirmation)
    @user=User.new(new_user)
    if @user.save
      flash[:success] = "Welcome to Ritly!"
      sign_in @user
      redirect_to @user
    else
      render'new'
    end
  end

  # Not used (but could provide update functionality)
  # def update
  #   @user = User.find(params[:id])
  #   @user.update_attributes(params[:user])
  #   render :show
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # SessionHelper manages @current_user, that's the user currently
  # signed in.

  # signs in supplied user, called from SessionController
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    # current_user is avilable in controllers and views!
    # This is an is an assignment, which we must define - see below
    # note that next line is a call to setter 'def current_user=(user)' below
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  # Authorization: signed_in_user is called in a before_filter
  # callback in each controller, see books/ingredients/recipe controllers
  # Ensures access to create/edit functions on if signed in.
  def signed_in_user
    unless signed_in?
      # If not signed in, save current location in session object
      # to be able to redirect after successful sign in.
      session[:return_to] = request.url
      # prompt sign in page
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  # signs out user by deleting @current_user and session cookie
  def sign_out
    @current_user = nil
    cookies.delete(:remember_token)
  end

  # Getter and setter for @current_user
  def current_user=(user)
    @current_user = user
  end

  # if current_user doesn't exist, check session cookie for user session
  # If exists, get the user record that belongs to that session.
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button><a class="navbar-brand" href="#">Ritly!</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><a href="/rlinks">Home</a></li>
      <li ><a href="/rlinks/new">Add Link</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if signed_in? %>
        <li><%= link_to "My profile", current_user %></li>
        <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to "Sign up", signup_path %></li>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ritly</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render  partial: "layouts/nav_bar" %>

<%= yield %>

</body>
</html>

app/views/rlinks/edit.html.erb
<h2>Edit Link</h2>
<div class='col-md-6'>
<%= form_for @rlink do |rl| %>
	<div class="form-group">
		<%= label_tag(:link, "Target URL:") %>
		<%= rl.text_field(:link, value: @rlink.link, class: "form-control") %>
	</div>
	<div class="form-group">
  		<%= label_tag(:random_string, "Link Token:") %>
  		<%= rl.text_field(:random_string, value: @rlink.random_string, class: "form-control") %>
	</div>
  	<%= rl.submit("Update", class: "btn btn-primary") %>
<% end %>
</div>

app/views/rlinks/index.html.erb
<h2>Active Links</h2>
  <div class='col-md-12'>
	<table class="table table-bordered">
		<tr>
			<th>ID</th>
			<th>Target URL</th>
			<th>Link Token</th>
			<th>Created</th>
			<th>Updated</th>
		</tr>
		<% @rlinks.each do |rlink| %>
			<tr>
				<td><a href="/rlinks/<%= rlink.id %>"><%= rlink.id %></a></td>
				<td><%= rlink.link %></td>
				<td><%= rlink.random_string %></td>
				<td><%= rlink.created_at %></td>
				<td><%= rlink.updated_at %></td>
			</tr>
		<% end %>
	</table>
</div>

app/views/rlinks/new.html.erb
<h2>New Link</h2>
<div class='col-md-6'>
<%= form_for @rlink do |rl| %>
	<div class="form-group">
		<%= label_tag(:link, "Target URL:") %>
		<%= rl.text_field(:link, class: "form-control") %>
	</div>
	<div class="form-group">
  		<%= label_tag(:random_string, "Link Token:") %>
  		<%= rl.text_field(:random_string, class: "form-control") %>
	</div>
  	<%= rl.submit("Create", class: "btn btn-primary") %>
<% end %>
</div>

app/views/rlinks/show.html.erb
<h2>Selected Link</h2>
<div class='col-md-6'>
<form role="form">
	<fieldset disabled>
		  <div class="form-group">
    		<label for="inputDisplayID">ID</label>
    		<input type="text" class="form-control" id="inputDisplayID" placeholder="<%= @current_link.id %>">
  		</div>
  		<div class="form-group">
    		<label for="inputDisplayTargetURL">Target URL</label>
    		<input type="text" class="form-control" id="inputDisplayTargetURL" placeholder="<%= @current_link.link %>">
  		</div>
  		<div class="form-group">
    		<label for="inputDisplayLinkToken">Link Token</label>
    		<input type="text" class="form-control" id="inputDisplayLinkToken" placeholder="<%= @current_link.random_string %>">
  		</div>
  		<div class="form-group">
    		<label for="inputDisplayCreatedTimestamp">Created</label>
    		<input type="text" class="form-control" id="inputDisplayCreatedTimestamp" placeholder="<%= @current_link.created_at %>">
  		</div>
  		<div class="form-group">
    		<label for="inputDisplayUpatedTimestamp">Last Updated</label>
    		<input type="text" class="form-control" id="inputDisplayUpdatedTimestamp" placeholder="<%= @current_link.updated_at %>">
  		</div>
	</fieldset>
</form>
<%= link_to "Edit", edit_rlink_path(@current_link), class: "btn btn-warning" %>
<%= link_to "Delete", @current_link, method: :delete, class: "btn btn-danger", data: { confirm: "Delete this link: Are you sure?" } %>
</div>

app/views/rlinks/token_not_found.html.erb
<!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Begin page content -->
      <div class="container">
        <div class="page-header">
          <h1>Look up token not found.</h1>
        </div>
        <p class="lead">Please check your look up token and matching URL.</p>
        <p>Use <a href="/rlinks">the Ritly index list</a> if need be.</p>
      </div>
    </div>

    <div id="footer">
      <div class="container">
        <p class="text-muted">&copy; Ritly 2014</p>
      </div>
    </div>

app/views/users/new.html.erb
<h2>Sign up</h2>
<div class='col-md-6'>
  <%= form_for(@user) do |f| %>
    <% unless @user.errors.count == 0   %>
      <div class="alert alert-error">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
	<div class="form-group">
      <%= f.label(:name) %>
      <%= f.text_field(:name, class: "form-control") %>
	</div>
	<div class="form-group">
      <%= f.label(:email) %>
      <%= f.text_field(:email, class: "form-control") %>
	</div>
	<div class="form-group">
      <%= f.label(:password) %>
      <%= f.password_field(:password, class: "form-control") %>
	</div>
	<div class="form-group">
      <%= f.label(:password_confirmation, "Confirmation") %>
      <%= f.password_field(:password_confirmation, class: "form-control") %>
	</div>
    <%= f.submit("Create my account", class: "btn btn-large btn-primary") %>
  <% end %>
</div>

app/views/users/show.html.erb
<h2>User Profile</h2>
<div class='col-md-6'>
  <form role="form">
	<fieldset disabled>
	  <div class="form-group">
    	  <label for="inputDisplayName">Name</label>
    	  <input type="text" class="form-control" id="inputDisplayName" placeholder="<%= @user.name %>">
  	  </div>
	  <div class="form-group">
    	<label for="inputDisplayEmail">Name</label>
    	<input type="text" class="form-control" id="inputDisplayEmail" placeholder="<%= @user.email %>">
  	  </div>
  	</fieldset>
  </form>
</div>